version = 1

[approve]
auto_approve_usernames = ["dependabot"]

[merge.message]
include_coauthors = true
include_pull_request_url = true

[merge.automerge_dependencies]
# auto merge all PRs opened by "dependabot" that are "minor" or "patch" version upgrades. "major" version upgrades will be ignored.
versions = ["minor", "patch"]
usernames = ["dependabot"]
